version: '3'
services:
  web:    
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
    depends_on:
        - db
    env_file: ../.env
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: host.docker.internal
    ports:
        - 3000:3000
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    network_mode: service:db

  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    env_file: ../.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   